name: Run Tests

on: [push]

jobs:
  code-checks:
    strategy:
      fail-fast: false
      matrix:
        tools:
          - command: "mypy"
          - command: "pylint"
          - command: "pre-commit"
    name: code check - ${{ matrix.tools.command }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: set up uv
        uses: astral-sh/setup-uv@v6
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"
      - name: install dependencies
        run: make install-ci
      - name: ${{ matrix.tools.command }}
        run: make ${{ matrix.tools.command }}
  test:
    strategy:
      matrix:
        python: ["3.11", "3.12", "3.13"]
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: set up uv
        uses: astral-sh/setup-uv@v6
      - name: setup up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: install dependencies
        run: make install-ci
      - name: pytest
        run: uv run pytest
