name: Run Tests

on: [push]

jobs:
  code-checks:
    strategy:
      fail-fast: false
      matrix:
        tools:
          - command: ["mypy", "./feldfreund_devkit", "--non-interactive", "--install-types"]
          - command: ["pylint", "./feldfreund_devkit"]
          - command: ["pre-commit", "run", "--all-files"]
    name: code check - ${{ matrix.tools.command[0] }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: set up Poetry
        uses: abatilo/actions-poetry@v4
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"
      - name: install dependencies
        run: poetry install --with dev --no-root
      - name: ${{ matrix.tools.command[0] }}
        run: poetry run ${{ join(matrix.tools.command, ' ') }}
  test:
    strategy:
      matrix:
        python: ["3.11", "3.12", "3.13"]
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: set up Poetry
        uses: abatilo/actions-poetry@v4
      - name: setup up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: "poetry"
      - name: install dependencies
        run: poetry install --with test --no-root
      - name: pytest
        run: poetry run pytest
